version: "3"

services:
  db:
    container_name: reserve_system_db
    image: postgres
    volumes:
      - ./postgres:/var/lib/postgresql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db

  web:
    container_name: reserve_system_web
    build: .
    volumes:
      - .:/code
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - db